<?php
/*
 *  This file is part of the Term Frequency Analyzer.
 *
 *  (c) Alexander Smyslov <kokoc.smyslov@yandex.ru>
 *
 *  For the full copyright and license information, please view the LICENSE
 *  file that was distributed with this source code.
 */
 echo '<' . '?' . 'php' ?> 
declare(encoding = 'utf-8');
// This file is autogenerated at <?php echo date('r') ?>, don`t change it!

<?php foreach($all_constants as $consts): ?>
// consts for <?php echo $lang = $consts->getLanguage() ?> language
// part of speech
<?php foreach($consts->getPosesMap() as $item): ?>
/**
 * <?php echo $helper->posConstName($consts, $item['const']), ' ', '"', $item['name'], '" part of speech'; ?>
 */
define('<?php echo $helper->posConstName($consts, $item['const']) ?>', <?php echo $item['id'] ?>);
<?php endforeach; ?>
    
// grammems
<?php foreach($consts->getGrammemsMap() as $item): ?>
/**
 * <?php echo $helper->grammemConstName($consts, $item['const']), ' ', '"', $item['name'], '" grammem'; ?>
 */
define('<?php echo $helper->grammemConstName($consts, $item['const']) ?>', <?php echo $item['id'] ?>);
<?php endforeach; ?>

// meta grammems
<?php foreach($consts->getMetaGrammemsMap() as $item): ?>
function <?php echo $helper->grammemConstName($consts, $item['const']) ?>() { return <?php echo $helper->metaGrammemConstValue($consts, $item['consts_list']) ?>; }
<?php endforeach; ?>

<?php endforeach; ?>
